
let PizzaList = [
 {
    id: 1,
    name: "Mussarela",
    img: "pizza5.png",
    prices: [24.99, 24.99, 24.99],
    sizes: ["000g", "000g", "000g"],
    description:"musssrela e requeijão.",
  },
 {
    id: 2,
    name: "Alho e Óleo",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 3,
    name: "Marguerita",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 4,
    name: "Portuguesa",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 5,
    name: "Bacon",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 6,
    name: "Calabresa",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 7,
    name: "Baiana",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },

 {
    id: 8,
    name: "Moda da casa",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 9,
    name: "Três Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },

  {
    id: 10,
    name: "Frango com Catupiry",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },

  {
    id: 11,
    name: "Vegetariana",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
];
