
let PizzaList = [
 {
    id: 1,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 2,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 3,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 4,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 5,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 6,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 7,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },

 {
    id: 8,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
 {
    id: 9,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },

  {
    id: 10,
    name: "Quatro Queijos",
    img: "pizza5.png",
    prices: [10.0, 15.0, 17.45],
    sizes: ["320g", "530g", "860g"],
    description:"Se é queijo que você quer @, então essa pizza é para você!",
  },
];